### ISSUE TITLE
Suggestion for a missing box art for Jade Cocoon

### ISSUE THREAD

**Issue by TheSyldat** [libretro-thumbnails/libretro-thumbnails#65]
Howdy I'm completly new to github so pardon me if it's not the right place for this

Thing is the French version of Jade Cocoon is listed in the data base of retro arch but it's missing its box art 

The French version of Jade Cocoon is known in the data base as :
Jade Cocoon - La Legende de Tamamayu [SLES-02202]

Here is a clean looking scan in PNG file format with 512 pixels of width :

https://cdn.discordapp.com/attachments/217230000489758723/666279951573450772/PS1_F_Jade_Cocoon_-_La_Legende_de_Tamamayu_SLES-02202.png

Can someone add it please ?

**Comment by MarcoEstevez** [comment]
Sure, I will look into it, and add it add it as soon as possible :-D

**Comment by TheSyldat** [comment]
Thanks let me know when it's added so that I can make a refresh of the tumbnails .

**Comment by MarcoEstevez** [comment]
Done in here https://github.com/libretro-thumbnails/Sony_-_PlayStation/pull/82

**Comment by TheSyldat** [comment]
And yet retroarch still doesn't download it for some reason :(

**Comment by MarcoEstevez** [comment]
Ummm...  I see, I think it will require some additional steps @RobLoach do you know how are thumbnails trasfered to RA delivery service?

**Comment by TheSyldat** [comment]
Just performed a search in the database it seems the french entry hasn't been added just yet..

**Comment by RobLoach** [comment]
It could be the UTF8 that's messing things up:
- http://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Boxarts/?dasffads
- http://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Boxarts/Jade%20Cocoon%20-%20La%20L%C3%A9gende%20De%20Tamamayu%20%28Europe%29.png

**Comment by TheSyldat** [comment]
Wow yeah Apparently it is indeed in the database 

maybe by deleting the accentuated e and replacing it with regular E ( I mean at this point we're kind of used to programmers not giving a shit about HUMAN wrriting of non english humans using more thannn 28 letters in theirr alphabet .... )

It's not like it's the first and it won't be the last time either that french (and otherr languages) have to butcher themselves up just to "fit" (sic) the digital age ...

**Comment by TheSyldat** [comment]
Dunno if changes were made or not but now it downloads the box art just fine 

Sooo I think I can close that one ?
